/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "BondTracker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BondTracker__factory>;
    getContractFactory(
      name: "CommonPartiallyOwned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonPartiallyOwned__factory>;
    getContractFactory(
      name: "CommonPartialReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonPartialReceiver__factory>;
    getContractFactory(
      name: "CommonPartialToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonPartialToken__factory>;
    getContractFactory(
      name: "CommonPartiallyOwnedEnumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonPartiallyOwnedEnumerable__factory>;
    getContractFactory(
      name: "TreasuryOwnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TreasuryOwnable__factory>;
    getContractFactory(
      name: "Sphinxes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Sphinxes__factory>;
    getContractFactory(
      name: "SphinxContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SphinxContract__factory>;
    getContractFactory(
      name: "Treasury",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Treasury__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
